version: '3.8'

services:
  nginx: 
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - apache

  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    expose:
      - "80"
